### ISSUE TITLE
Add a Changelog/Release Notes

### ISSUE THREAD

**Issue by coliff** [Rundiz-WP/bootstrap-basic4#26]
It'd be good to adda changelog or Release Notes somewhere so users can see what is changed in each update. Maybe add a `CHANGELOG.md` or add it as a section to the readme.txt.

**Comment by ve3** [comment]
Agree.

**Comment by ve3** [comment]
[https://themes.trac.wordpress.org/ticket/62944](https://themes.trac.wordpress.org/ticket/62944)
