### ISSUE TITLE
How to include child theme css?

### ISSUE THREAD

**Issue by MastaBaba** [Rundiz-WP/bootstrap-basic4#33]
I'm used to doing something like this for child themes:

```
	    wp_enqueue_style( "bootstrap-basic4-style", get_template_directory_uri() . '/style.css', array(), filemtime(get_template_directory_uri() . '/style.css') );

	    wp_enqueue_style( 'child-style',
	        get_stylesheet_directory_uri() . '/style.css',
	        array( "bootstrap-basic4-style"  ),
	        filemtime(get_stylesheet_directory() . '/style.css')
	    );
```

But, I find that this includes my child theme styles twice.

If I completely leave out the above, both the css of the parent theme and of the child theme are included.

However, I then don't see a way of managing versioning of the child theme's css. Updating the version in the header appears to have no effect. Like so:

```
/*
 Theme Name:   my child theme
 Description:  A theme based on bootstrap basic 4
 Author:       Babak Fakhamzadeh (that's me)
 Template:     bootstrap-basic4
 Version:      1.0.12
 Text Domain:  my-text-domain
*/

```

How to properly include a css file of a child theme?

**Comment by ve3** [comment]
In my theme, `wp_enqueue_style('bootstrap-basic4-parent-style', get_template_directory_uri() . '/style.css');` will be called parent (Bootstrap Basic 4) **style.css** and child theme **style.css** will be called automatically with the handle name from parent theme.
So, `wp_enqueue_style( 'child-style'...` is no need. (I don't see calling style.css in any part in my child theme).

**Comment by MastaBaba** [comment]
Right, I noticed this works, indeed.

But, this often results in Wordpress serving a cached version of my child theme css file, not a recently updated version.

**Comment by ve3** [comment]
Maybe try this before enqueue them both again. `wp_dequeue_style('bootstrap-basic4-wp-main');`.

Please tell me if this work.

**Comment by MastaBaba** [comment]
Yes, this appears to work. Thanks.

I now have this:

```
	wp_dequeue_style( 'bootstrap-basic4-wp-main');
	wp_enqueue_style( "bootstrap-basic4-wp-main", get_template_directory_uri() . '/style.css' );

	wp_enqueue_style( 'child-style',
	        get_stylesheet_directory_uri() . '/style.css',
	        array( "bootstrap-basic4-wp-main"  ),
	        filemtime(get_stylesheet_directory() . '/style.css')
	);
```
