### ISSUE TITLE
How to include popper.js?

### ISSUE THREAD

**Issue by MastaBaba** [Rundiz-WP/bootstrap-basic4#34]
I want to use popovers in my theme. How do I include popper.js, it being required to be loaded before bootstrap.js?

**Comment by ve3** [comment]
popper is already in bootstrap.bundle.js, bootstrap.bundle.min.js
[Reference](https://getbootstrap.com/docs/4.1/getting-started/contents/).

**Comment by MastaBaba** [comment]
In that case, there appears to be a bug.

When I call this:

`$('[data-toggle="popover"]').popover();`

I get this:

> TypeError: $('[data-toggle="popover"]').popover is not a function. (In '$('[data-toggle="popover"]').popover()', '$('[data-toggle="popover"]').popover' is undefined)

You can see this work/fail in practice by going here:

https://visitthisreadthat.com

You would have to register and then visit the homepage again to see this problem... pop up.

**Comment by ve3** [comment]
Your theme did not load bootstrap JS correctly or it was loaded but messed up with something while in bundle/cache/miniff process.

Try to prevent merging the CSS and JS files and reload the page again if it works because my theme itself (Bootstrap Basic 4) and the child theme that use BB4 is working properly.
Input `jQuery('[data-toggle="popover"]').popover();` return object correctly.

**Comment by MastaBaba** [comment]
I use the plugin Autoptimize. But, turning that plugin off makes no difference (I just tried).

When I have Autoptimize turned off and do a 'live preview' with your theme, I also can not call popovers.

**Comment by MastaBaba** [comment]
I now have Autoptimize turned off. You can inspect the header of the URL above and see that bootstrap.bundle is loaded:

`<script type="text/javascript" src="https://visitthisreadthat.com/wp-content/themes/bootstrap-basic4/assets/js/bootstrap.bundle.min.js?ver=4.3.1"></script>`

**Comment by ve3** [comment]
Your file **bootstrap-basic4-vtrt/assets/js/custom.js** is loaded before bootstrap JS **bootstrap-basic4/assets/js/bootstrap.bundle.min.js**.

When you [enqueue](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) it, add the bootstrap 4 JS as dependency.
Refer bootstrap handle from this ( https://github.com/Rundiz-WP/bootstrap-basic4/blob/master/inc/classes/BootstrapBasic4.php ).

```
wp_enqueue_script('your-handle', 'your-js-file.js', ['bootstrap4-bundle'], 'your-theme-version', true);
```

**Comment by MastaBaba** [comment]
You're correct. Thanks for spotting.

That makes me wonder how the popup didn't work when I was live-previewing your theme, but, eh, if this works, it works :)

Thanks again.
