### ISSUE TITLE
Removing the borders

### ISSUE THREAD

**Issue by aflove65** [Rundiz-WP/bootstrap-basic4#35]
how do i remove the borders that appear on the pages when I make a page?

**Comment by ve3** [comment]
What borders?

**Comment by aflove65** [comment]
https://i.imgur.com/hTlzFMV.png 

These borders are on all of my pages.

**Comment by ve3** [comment]
I cannot help you without any information such as the URL that have this problem, HTML elements and class that you use.
I cannot inspect anything from picture(s).

**Comment by aflove65** [comment]
http://www.minxi.online/links/


                <main id="main" class="col-md-<?php echo
\BootstrapBasic4\Bootstrap4Utilities::getMainColumnSize(); ?> site-main"
role="main"> in single page under theme editor is where i "think" the
problem is.

**Comment by ve3** [comment]
It is come from **assets/css/main.css** on line 158 (158 - 164). 
This is default style just to make it easy to see each block area. 

To override these styles, you may need to learn about web browser tools such as **inspect element** on Google Chrome or Firefox.
Here is [the link for Firefox](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector).
Here is [the link for Google Chrome](https://developers.google.com/web/tools/chrome-devtools).

**Comment by aflove65** [comment]
If I knew how to do that I wouldn't have asked for help but thanks
anyways... I'll figure it out.

**Comment by ve3** [comment]
You asked question and I have told you everything. I point you to the problem. File, Line of the style that you can override it.
I even advice you about tools and links to learn more because these can help you work faster in the future.
So, what do you want?
