### ISSUE TITLE
How to customize theme using CSS/SCSS (child theme)?

### ISSUE THREAD

**Issue by piasm** [Rundiz-WP/bootstrap-basic4#36]
Hi,

I've created a child theme and in my style.css, I've added for example 

` body { background-color: #000; } `.

This does not have an effect as it is being overridden by _reboot.scss. 
So I tried creating style.scss and changing the variable as per the Bootstrap Documentation:

```
$body-bg: #000;

@import "../bootstrap-basic4/assets/css/bootstrap";
```

Again, it doesn't have an effect.

I can't seem to override any of the existing styling in the CSS. If I add a new rule to the style.css or style.scss, it does work.

What am I doing wrong? Thanks!

**Comment by ve3** [comment]
https://developer.wordpress.org/themes/advanced-topics/child-themes/
Make sure that you enqueue CSS correctly and it was loaded in browser's development (network) tool (network).

Bootstrap Basic 4 did not use **.scss** file, there are only css files. ( see asset files here https://github.com/Rundiz-WP/bootstrap-basic4/tree/master/assets )
All you see .scss in the inspect element is the result from .map, it is not real .scss file. Add or change those variables don't change anything.

To override styles, make sure that you enqueue CSS correctly as I mentioned above and [some case](https://github.com/Rundiz-WP/bootstrap-basic4/issues/33) you may need to dequeue and then enqueue again.

**Comment by piasm** [comment]
Thanks for your fast response. I have this in my functions.php, which is obviously wrong as it doesn't override anything. Still trying to fix it.

```
<?php

add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {

    $parent_style = 'bootstrap-basic4'; 

    wp_enqueue_style($parent_style, get_template_directory_uri() . '/style.css', array(), rand(111, 9999), 'all');
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );

    wp_enqueue_style('bootstrap-reboot-style', get_stylesheet_directory_uri() .'/assets/css/bootstrap-reboot.css');
    wp_enqueue_style('main-style', get_stylesheet_directory_uri() . '/assets/css/main.css');
    wp_enqueue_style('bootstrap-style', get_stylesheet_directory_uri() . '/asssets/css/bootstrap.css');
}
?>

```

**Comment by ve3** [comment]
I hope that it was fixed now.
