### ISSUE TITLE
How to adjust public function displayComments

### ISSUE THREAD

**Issue by theRealHal9000** [Rundiz-WP/bootstrap-basic4#37]
Hi there,

Then client I'm working with has requested that I add the number of the comment in the list of comments on a post. I've figured out how to do this by editing Bootstrap Basic 4 directly, but I'd like to move my customization to a child theme so that I can update my Bootstrap Basic 4 to the latest version. 

I'd like to simply replace the existing displayComments public function from /inc/classes/Bsb4Design.php with a version in my child theme. I've looked online for tips on how to do this but results are less clear when it's a function within a class.

Thank you for your help!

**Comment by ve3** [comment]
The `displayComments` method of `Bsb4Design` class will be called from **/comments.php** file.
You can directly edit this file in your child theme, if you don't have it you can create it in your child theme.

Here are the document and examples.
https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/comment-template/

https://www.gavsblog.com/blog/adding-comments-to-a-wordpress-theme-template

https://www.wpexplorer.com/better-wordpress-comments/

https://developer.wordpress.org/reference/functions/get_comments_number/
