### ISSUE TITLE
Single post pagination doesn't show

### ISSUE THREAD

**Issue by iceytina** [Rundiz-WP/bootstrap-basic4#38]
Hello - I can't find where or how to enable or show single post pagination for blog posts. I've looked in the theme PHP code and see that there's pagination actually set, but nothing I do to alter that code will cause the pagination to show? Even deleting it and adding in my own pagination PHP from Wordpress.org fixes this. I also deactivated all my plugins to see if one of them was interfering with this. No luck. Using the default, unedited theme also doesn't show pagination. I'm not a hard-core PHP programmer, so my ability to understand and alter PHP is limited.

How to get the pagination to show? Thanks.

**Comment by ve3** [comment]
Do you add `<!--nextpage-->` in your content?
Without this, the pagination inside a single post (full post page) will not work.

If you are using classic editor (TinyMCE), use **Insert** menu > and **Page Break** sub menu.
If you are using new editor, use **[+]** button and select **Page Break**.

The single post template is in **single.php** file and then it call to **template-parts/contentXXX.php** where **XXX** is empty, **-aside**, **-attachment**, etc depend on its format.
In these pages call to `wp_link_pages()` function which make `<!--nextpage-->`  split into pages and pagination links will be appears.

**Comment by iceytina** [comment]
Hi there -- 

 is old-school Wordpress for a post archive/category page, to cut off the text shown with a 'read more' or 'read full post' link? Not for bottom-of-a-single-post next/prev pagination? I've used quite a few themes that automatically add the next/prev post pagination below the post content when there's more than 1 post in the same category. However, I went ahead and tried this by inserting  in an HTML block at the bottom of 2 of my post's content. I'm using SiteOrigin Pagebuilder. I also added  to a post that uses the Classic Editor. Pagination didn't show there either.

I also already explored single.php and the content-XXX.php files and saw the PHP code:

```
    <?php 
    /**
     * This wp_link_pages option adapt to use bootstrap pagination style.
     */
    wp_link_pages(array(
      'before' => '<div class="page-links">' . __('Pages:', 'bootstrap-basic4') . ' <ul class="pagination">',
      'after'  => '</ul></div>',
      'separator' => ''
    ));
    ?> 
```

This is why I' mconfused. The pagination code is here. Why doesn't it actually show on the front-end single blog posts? I have several posts in this category and none of them are showing pagination. Help...

**Comment by ve3** [comment]
Read more is for cut the content to show in listing page such as home page, search result, category page, etc.
Read more is not for pagination.

To use pagination in the content you have to use **Page Break** as I said before.

To customize how many post will be display on home page, category listing page, etc. You can change the number in **Settings** > **Reading** > **Blog pages show at most**.

I'm never use any of those plugins you said. So, I cannot suggest anything based on those plugins.

The link below is the screenshot on my computer that have just new WP installed with this theme, no plugins. My post items per page is 1 and there are total 2 posts. My newest post contain **Page Break** for 3 pages and everything work fine in listing page.
https://postimg.cc/pyYFrDLD

The link below is showing when I click to read the latest post, it is **single.php** page. The **Page break** pagination also working fine.
https://postimg.cc/ygCDYdqQ

**Comment by iceytina** [comment]
The 'show at most' under reading isn't what's going on. That's for showing posts in a blog archive (category listing page), isn't it? Not a single, individual blog post. Like here's a single post: https://soniclegacyonline.com/newsletters/june-3rd-2020-issue-6-nearly-complete/
Pagination not showing on this.

Category listing page for this: https://soniclegacyonline.com/category/newsletters/
Not concerned about pagination on this.

I'll just have to try to work on this further. It's not my plugins, since, as I stated, I had deactivated them all to see if that would fix this. I had also rolled back all my CSS to basically an empty file and that also did nothing.

So confusing.

**Comment by ve3** [comment]
Please make sure that `<!--nextpage-->` was added in the HTML source view or use **Page Break** as I described above and maybe try again with new/clean WordPress install using default theme and this theme to see that pagination in single page is really working.
You may try this on your PC not on the real server.
If everything works fine, you may start from there step by step to see that what make your site pagination in the single post stop working.

**Comment by iceytina** [comment]
Yep I made sure  was in the HTML source yesterday in 2 posts. Didn't work. I used the HTML CODE block in my pagebuilder, so there wouldn't be any potential of WP messing up the code.

I'll make a fresh install and look into this...

**Comment by iceytina** [comment]
Okay. 100% new install, new db. No customizing. No plugins etc. Pagination still doesn't show: https://wordpress.cnroberts.com/newsletters/may-1-2020-issue-6-status/

It will show on the category listing page, but not single.php basically. So confused?

**Comment by iceytina** [comment]
Okay I modified the most again, but nextpage just splits that single post into 2 pages? The pagination doesn't take me to a completely different post? ...

**Comment by ve3** [comment]
Does this happen with the other themes? How is it with default theme such as Twenty-twenty?

I'm searched and found this is very good tutorial for you maybe it can help. https://www.wpbeginner.com/wp-tutorials/how-to-split-wordpress-posts-into-multiple-pages/

The `nextpage` tag must be put into where you want to split the content.
Example:

```
<p>paragraph1</p>
<!--nextpage-->
<p>paragraph2</p>
```
The paragraph 1 will be on page 1 and paragraph 2 will be on page 2.

**Comment by iceytina** [comment]
It doesn't happen with other themes. I had used twenty twenty on this new install before then swapping to your theme. And I shouldn't have to put any kind of nextpage code at the bottom of each single post on a single blog post page? I never have had to do that before. It's always been automated in any theme I've used.

I just switched back to twenty twenty and their theme's pagination does what I want: different next post or different previous post. Not splitting the same post into multiple pages with pagination: https://wordpress.cnroberts.com/newsletters/may-1-2020-issue-6-status/

But you can also see the nextpage pagination (Pages: 1 2) on twenty twenty above the regular pagination (
← March 1, 2020 – A new year, new challenges // → June 3rd, 2020 – Issue 6 NEARLY Complete!), so these two things are separate?

The tutorial you sent is good if a person wants to split 1 post into 2+ pages. I don't want to do that. I literally just want the normal pagination that will take a person to a completely  different post published before or after the current post.

Does your theme not do that? Your screen shots don't show if that's the case. Just that there's some form of visual pagination at the bottom of single posts.

**Comment by ve3** [comment]
OK, I'm sorry about that. I can understand now that you want is **next/previous post** in a **single post** page.

This theme by default don't have it based on concept:
> The concept is to keep it basic, no rich features, no additional functions
(see more on readme.txt of this theme).

However, you can use this code to add next/previous post in your single.php child theme (or this theme if you modify it to be yours).
```php
$next_post = get_next_post();
$prev_post = get_previous_post();

if ($next_post || $prev_post) {

	$pagination_classes = '';

	if ( ! $next_post ) {
        $pagination_classes = ' only-one only-prev';
	} elseif ( ! $prev_post ) {
        $pagination_classes = ' only-one only-next';
	}

    if ($prev_post) {
?>

    <a class="previous-post" href="<?php echo esc_url(get_permalink($prev_post->ID)); ?>">
        <span class="arrow" aria-hidden="true">&larr;</span>
        <span class="title"><span class="title-inner"><?php echo wp_kses_post(get_the_title($prev_post->ID)); ?></span></span>
    </a>

<?php
    }

    if ($next_post) {
?>

    <a class="next-post" href="<?php echo esc_url(get_permalink($next_post->ID)); ?>">
        <span class="arrow" aria-hidden="true">&rarr;</span>
        <span class="title"><span class="title-inner"><?php echo wp_kses_post(get_the_title($next_post->ID)); ?></span></span>
    </a>
<?php
    }
}
```
This code is copied from **TwentyTwenty** theme > **template-parts/navigation.php** file.
Put this code in **single.php** file below the line number 24.
Example:
```php
$Bsb4Design->pagination();
echo "\n\n";
// next/previous post should be here.
```

---
Full **single.php** file example:
```php
<?php
/** 
 * The single post.<br>
 * This file works as display full post content page and its comments.
 * 
 * @package bootstrap-basic4
 */


// begins template. -------------------------------------------------------------------------
get_header();
get_sidebar();
?> 
                <main id="main" class="col-md-<?php echo \BootstrapBasic4\Bootstrap4Utilities::getMainColumnSize(); ?> site-main" role="main">
                    <?php
                    if (have_posts()) {
                        $Bsb4Design = new \BootstrapBasic4\Bsb4Design();
                        while (have_posts()) {
                            the_post();
                            get_template_part('template-parts/content', get_post_format());
                            echo "\n\n";

                            $Bsb4Design->pagination();
                            echo "\n\n";

// additional function. next/previous post.
$next_post = get_next_post();
$prev_post = get_previous_post();

if ($next_post || $prev_post) {

	$pagination_classes = '';

	if ( ! $next_post ) {
        $pagination_classes = ' only-one only-prev';
	} elseif ( ! $prev_post ) {
        $pagination_classes = ' only-one only-next';
	}

    if ($prev_post) {
?>

    <a class="previous-post" href="<?php echo esc_url(get_permalink($prev_post->ID)); ?>">
        <span class="arrow" aria-hidden="true">&larr;</span>
        <span class="title"><span class="title-inner"><?php echo wp_kses_post(get_the_title($prev_post->ID)); ?></span></span>
    </a>

<?php
    }

    if ($next_post) {
?>

    <a class="next-post" href="<?php echo esc_url(get_permalink($next_post->ID)); ?>">
        <span class="arrow" aria-hidden="true">&rarr;</span>
        <span class="title"><span class="title-inner"><?php echo wp_kses_post(get_the_title($next_post->ID)); ?></span></span>
    </a>
<?php
    }
}
// end next/previous post.

                            // If comments are open or we have at least one comment, load up the comment template
                            if (comments_open() || '0' != get_comments_number()) {
                                comments_template();
                            }
                            echo "\n\n";
                        }// endwhile;

                        
                        unset($Bsb4Design);
                    } else {
                        get_template_part('template-parts/section', 'no-results');
                    }// endif;
                    ?> 
                </main>
<?php
get_sidebar('right');
get_footer();
```

I hope that it is working the way you want now. 😄

**Comment by iceytina** [comment]
That worked. Thanks for communicating so much and posting that code! I super appreciate it.

**Comment by ve3** [comment]
https://github.com/Rundiz-WP/bootstrap-basic4/commit/6dd9e6ac78a7407151c884a9e8b5e0b967fccd5e
