### ISSUE TITLE
Add Featured Image

### ISSUE THREAD

**Issue by ivanshim** [Rundiz-WP/bootstrap-basic4#39]
To get a featured image, could I suggest adding the following code or something similar

```
<?php
    if ( has_post_thumbnail() ) {
      echo '<p>';
      the_post_thumbnail( 'full', [ 'class' => 'img-fluid rounded' ] );
      echo '</p>';
    }
?>
```

inside the file:

template-parts/content-page.php

between the_title , and the_content

**Comment by ve3** [comment]
You can do that on your child theme. 
If I add this thing, the theme design will change and it will be affect many users.
And I'm sure that if that happens, many of them have to try to remove it from their theme and they will not happy.

I couldn't make changes anything that is already displayed. It will be affect many many users.

The theme concept is in readme.txt file from the first time.

> The concept is to keep it basic, no rich features, no additional functions; all of these for theme developers will be easier to start develop their theme.
> If the theme contain too many options, some of those options maybe no need by the others it will be waste of time to find and remove.
> It is still keep the same concept as Bootstrap Basic (version 1) which is minimal, just basic, easy to start build your own theme whether it is for new parent theme or child theme.
