### ISSUE TITLE
bootstrap-basic5

### ISSUE THREAD

**Issue by coliff** [Rundiz-WP/bootstrap-basic4#40]
Heya! Do you have plans to add a new 'bootstrap-basic5' theme based on Bootstrap 5?
https://getbootstrap.com/

**Comment by ve3** [comment]
I'm sorry, I don't think so.

WordPress have a lot more rules regarding to theme submissions.
Some of their rules seems to be more difficult for a theme like this (theme for developer).
For example: they do not allow **.map** including in the theme files, while **.map** files help theme developers a lot!

You or whoever can use this name **Bootstrap basic x**, or **Bootstrap-basic x** (where x is number) to create and publish the theme.
It's okay, I don't reserve it and no need to mention to me. :-)

If there is any need for help, you can always tell me.
