### ISSUE TITLE
No sub-sub-menus showing

### ISSUE THREAD

**Issue by xxxmicrobexxx** [Rundiz-WP/bootstrap-basic4#43]
I have a main menu with drop down sub-menus, this works as expected.

However I have added an additional sub menu to one item and there is no open icon to expand the item and view the additional menu items.

If I switch to a generic theme (TwentyFifteen) I can open another layer of menu items.

Is this a bug?

**Comment by ve3** [comment]
Bootstrap 4 only support 1 sub menu.
See the document here https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by xxxmicrobexxx** [comment]
Thanks for the prompt reply, but that doesn't make a lot of sense.

**Comment by ve3** [comment]
> Bootstrap v.4 basic theme. For build new theme based on Bootstrap 4. (WordPress 5 or Gutenberg ready.)
> The concept is to keep it basic, no rich features, no additional functions; all of these for theme developers will be easier to start develop their theme.
> If the theme contain too many options, some of those options maybe no need by the others it will be waste of time to find and remove.
> It is still keep the same concept as Bootstrap Basic (version 1) which is minimal, just basic, easy to start build your own theme whether it is for new parent theme or child theme.

Since the Bootstrap itself does not have this feature and the theme concept is to keep it basic, I could not add any additional feature.
I hope that you can find a good menu plugin to work with this.
