### ISSUE TITLE
Please help css make content fill page

### ISSUE THREAD

**Issue by lifesavings** [Rundiz-WP/bootstrap-basic4#44]
I would like to know how to increase the size of the main content area and sidebars so that the whole site fills the page on the desktop. Right now there are large margins on both sides and content appears small.

**Comment by ve3** [comment]
From document [here](https://getbootstrap.com/docs/4.4/layout/overview/) and question [here](https://stackoverflow.com/questions/33803767/need-to-create-wider-container-in-bootstrap-1920px)
You can use `container-fluid` class or override css in your child theme with this.
```
@include media-breakpoint-up(md) {
    .wide-container {
        max-width: 1470px; // limit the width here!
    }
}
```

Use browser inspector to help find out the class name, selector, value.

**Comment by ve3** [comment]
I hope that your problem was resolved, I will close the issue but if you have any more question you can comment anytime.

**Comment by lifesavings** [comment]
Yes I figured out the selector for main page, and it worked. I don't know
the selector for posts. Thanks.

**Comment by ve3** [comment]
The selector of `container` is the same on all pages not just main page. It use `get_header()` which is called to theme's header.php and here is the [source code in header.php](https://github.com/Rundiz-WP/bootstrap-basic4/blob/master/header.php)

The width of main column for all pages is using this code `col-md-<?php echo \BootstrapBasic4\Bootstrap4Utilities::getMainColumnSize(); ?>` and this class::method is in this file. ( https://github.com/Rundiz-WP/bootstrap-basic4/blob/master/inc/classes/Bootstrap4Utilities.php )<br>
It's calculate from (12 - (left sidebar size (if available) - right sidebar size (if available))).<br>
You can modify sidebar size in [functions.php](https://github.com/Rundiz-WP/bootstrap-basic4/blob/master/functions.php) in this theme or in your child theme, or every pages in your child theme you can manually set the number of column like this `col-md-8` instead.
