### ISSUE TITLE
Woocommerce search not working.

### ISSUE THREAD

**Issue by Hammer1980** [Rundiz-WP/bootstrap-basic4#46]
If I search 'Mix', even with a woocommerce search plug in the out put is below.

"Create your own bundle with Mix and Match.

Create your own bundle with Mix and Match.

MIX & MATCH

MIX & MATCH"

There are two products with the term in with one of each of the above in title and description.

This is all it shows. Just plain text. It works in other themes, just not this one. It does not show the woocommerce products.
Any idea to mak e this work ?

**Comment by ve3** [comment]
It is not possible that all themes will be supported WooCommerce. 
For example, one of popular Bootstrap ( Flat Bootstrap by XtremelySocial ) still not fully supported. The search result is just product title, description same as this theme.

You have to search for theme that has marked as WooCommerce supported. Example ( https://wordpress.org/themes/search/woocommerce/? ).

**Comment by ve3** [comment]
This theme has nothing about search result modification. If you disable all other plugins except Woo then it will be able to search the product but search result did not display product's thumbnail. It still be able to click on the link to see product description page.

So, what you said _It does not show the woocommerce products_ isn't true. WordPress can search across any different post types. Try to disable other plugins that may interfere the search result.
